# Generated by Django 4.2.4 on 2024-11-14 04:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.TextField()),
                ("heading", models.TextField()),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("content_heading", models.TextField()),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("your_message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DestinationCity",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="core.basemodel"),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="destinationcity_images/")),
                ("image_short_heading", models.TextField(blank=True, null=True)),
                ("image_short_text", models.TextField(blank=True, null=True)),
                ("description_heading", models.TextField(blank=True, null=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Destination City",
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="partners_logos/")),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="testimonial_images/")),
                ("full_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("review_star_count", models.PositiveIntegerField(default=5, help_text="Product Rating(max:5)", validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name="TouristDestination",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="core.basemodel"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", tinymce.models.HTMLField()),
                ("instant_confirmation", models.BooleanField(default=True)),
                ("mobile_ticket", models.BooleanField(default=True)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("prefernce", models.BooleanField(default=True)),
                ("popular_destination", models.BooleanField(default=False)),
                (
                    "common_age_note",
                    models.CharField(
                        blank=True,
                        default="Infants aged 3 and under can enter for free. Simply show their ID at the venue and enter.",
                        max_length=100,
                        null=True,
                        verbose_name="Common Age Note",
                    ),
                ),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.destinationcity")),
            ],
            options={
                "verbose_name_plural": "Tourist Destination",
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="ThingsToDo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="thingstodo_images/")),
                ("place_name", models.TextField()),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.destinationcity")),
            ],
        ),
        migrations.CreateModel(
            name="DestinationSpecification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("specification_heading", models.CharField(choices=[("Highlights", "Highlights"), ("Inclusions", "Inclusions")], default="Highlights", max_length=50)),
                ("specification_content", tinymce.models.HTMLField()),
                ("destination", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.touristdestination")),
            ],
        ),
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="tourist_destination_images/")),
                ("destination", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="web.touristdestination")),
            ],
        ),
    ]
