# Generated by Django 4.2.4 on 2024-11-14 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_packagedates"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PackageDates",
        ),
    ]
