# Generated by Django 4.2.4 on 2024-11-14 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_id", models.CharField(default=ticket.models.generate_order_id, max_length=220)),
                ("payable", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("is_ordered", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(blank=True, default="UAE", max_length=100, null=True)),
                ("booked_date", models.DateField(blank=True, null=True)),
                ("guest_adult", models.PositiveIntegerField(blank=True, null=True)),
                ("guest_child", models.PositiveIntegerField(blank=True, null=True)),
                ("ordered_at", models.DateTimeField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="TicketGroupPrice",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="core.basemodel"),
                ),
                ("age_group", models.CharField(choices=[("adult", "Adult"), ("children", "Children")], max_length=20)),
                ("age_note", models.CharField(blank=True, max_length=100, null=True, verbose_name="Ticket Age Limit Note")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("destination", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.touristdestination")),
            ],
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="core.basemodel"),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("validity_from_date", models.DateField(blank=True, null=True)),
                ("validity_end_date", models.DateField(blank=True, null=True)),
                ("status", models.BooleanField(default=False)),
                ("ticket_pdf", models.FileField(upload_to="tickets/")),
                ("group_price", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ticket.ticketgroupprice")),
            ],
            options={
                "unique_together": {("serial_number", "group_price")},
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ticket.order")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ticket.ticket")),
            ],
        ),
    ]
